// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17u1V8JsjpTvaEBk621w9ixsZQFUbMjk',
    appId: '1:625406883906:web:f2b4ae81fea29858bed5db',
    messagingSenderId: '625406883906',
    projectId: 'chatapp-875c2',
    authDomain: 'chatapp-875c2.firebaseapp.com',
    storageBucket: 'chatapp-875c2.appspot.com',
    measurementId: 'G-6D4JKPXTP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp7NHm8NnMZjH96QUqYjqKfDTo6b02pm8',
    appId: '1:625406883906:android:09040a3112297cbbbed5db',
    messagingSenderId: '625406883906',
    projectId: 'chatapp-875c2',
    storageBucket: 'chatapp-875c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4A1AHO_VOLXuCUoWknFogitr8vzlhegs',
    appId: '1:625406883906:ios:f722d547f73e59cabed5db',
    messagingSenderId: '625406883906',
    projectId: 'chatapp-875c2',
    storageBucket: 'chatapp-875c2.appspot.com',
    iosClientId: '625406883906-sodmg9lkv8jr87sjpg0e4afo0064n5q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemychat',
  );
}
